# This migration was autogenerated and is intentionally left empty to avoid applying
# index rename operations that are not valid for the current database.
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0003_make_user_non_nullable'),
    ]

    operations = []
