# Generated by Django 5.2.9 on 2025-12-10 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_payments_checkout_request_id_idx_payments_pa_checkou_e4cf10_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('export', 'Export'), ('delete', 'Delete'), ('other', 'Other')], default='view', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_checkou_e4cf10_idx',
            old_name='payments_checkout_request_id_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='payments_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_phone_n_483604_idx',
            old_name='payments_phone_number_idx',
        ),
        migrations.AddField(
            model_name='paymentaccesslog',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentaccesslog',
            index=models.Index(fields=['payment'], name='payments_pa_payment_4ef4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaccesslog',
            index=models.Index(fields=['user'], name='payments_pa_user_id_5bec72_idx'),
        ),
    ]
